# fly.toml app configuration file generated for cinemattr-api on 2023-05-14T16:09:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cinemattr-api"
primary_region = "yyz"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
